-- AlterTable
ALTER TABLE "Scratch" ADD COLUMN     "coverPosX" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "coverPosY" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "coverZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
